# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1efhLytAzzQCdwlPgGKtVvK_FxWQZqDHS
"""

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns


import os
for dirname, _, filenames in os.walk('/content/application_record.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

df = pd.read_csv('/content/application_record.csv')

df.head()

df['ID'].head()

df[df.CODE_GENDER == "M"]

df[(df.CODE_GENDER == "M") & (df['FLAG_OWN_CAR'] == "Y")]

df[(df.CODE_GENDER == "M") & (df['FLAG_OWN_CAR'] == "Y") & (df['NAME_INCOME_TYPE'] == "Working") & (df['NAME_FAMILY_STATUS'] == "Married")]

df.dtypes

df = df.astype({"CNT_FAM_MEMBERS":'int', "AMT_INCOME_TOTAL":'int'})

df.dtypes

df['CODE_GENDER'].replace('M',0,inplace=True)
df['CODE_GENDER'].replace('F',1,inplace=True)
df['FLAG_OWN_CAR'].replace('Y',0,inplace=True)
df['FLAG_OWN_CAR'].replace('N',1,inplace=True)
df['FLAG_OWN_REALTY'].replace('Y',0,inplace=True)
df['FLAG_OWN_REALTY'].replace('N',1,inplace=True)

df['NAME_INCOME_TYPE'] = df['NAME_INCOME_TYPE'].astype('category')
df['NAME_EDUCATION_TYPE'] = df['NAME_EDUCATION_TYPE'].astype('category')
df['NAME_FAMILY_STATUS'] = df['NAME_FAMILY_STATUS'].astype('category')
df['NAME_HOUSING_TYPE'] = df['NAME_HOUSING_TYPE'].astype('category')
df['OCCUPATION_TYPE'] = df['OCCUPATION_TYPE'].astype('category')

df.dtypes

df.head()

df.isnull().sum()

df = df.dropna(how='any',axis=0)

df.isnull().sum()

df.head()

df.groupby('FLAG_OWN_CAR').mean().head()

df.loc[df.NAME_INCOME_TYPE == 'Commercial associate'].plot(x='FLAG_EMAIL', y='FLAG_WORK_PHONE')

df['NAME_INCOME_TYPE'].hist()

df['NAME_FAMILY_STATUS'].hist()

df['NAME_HOUSING_TYPE'].hist()

from pylab import rcParams
sns.countplot(x='NAME_INCOME_TYPE',hue='FLAG_OWN_CAR',data=df)
rcParams['figure.figsize'] = 25, 10

sns.countplot(x='OCCUPATION_TYPE',hue='FLAG_OWN_CAR',data=df)

sns.set(rc={'figure.figsize':(15,3)})
plt.xticks(fontsize=15,rotation='vertical')
p=sns.countplot(df['NAME_INCOME_TYPE'],hue_order=df.groupby('NAME_INCOME_TYPE'))
p.axes.set_title("Amount of income per type",fontsize=30)
plt.show()

sns.set(rc={'figure.figsize':(10,3)})
df['AMT_INCOME_TOTAL']=df['AMT_INCOME_TOTAL'].astype(object)
df['AMT_INCOME_TOTAL'] = df['AMT_INCOME_TOTAL']/10000 
print(df['AMT_INCOME_TOTAL'].value_counts(bins=10,sort=False))
df['AMT_INCOME_TOTAL'].plot(kind='hist',bins=60,density=True)
plt.show()

sns.set(rc={'figure.figsize':(10,3)})
df['Age']=-(df['DAYS_BIRTH'])//365	
print(df['Age'].value_counts(bins=10,normalize=True,sort=False))
df['Age'].plot(kind='hist',bins=20,density=True)
plt.show()